### ISSUE TITLE
Include Instructions for Spinning Up App

### ISSUE THREAD

**Issue by crookedneighbor** [AntJanus/hRPG-lite-redux#8]
The readme does not include any instructions and there are no npm scripts for building assets or running the page.

**Comment by AntJanus** [comment]
sorry about that :) I'm adding preliminary installation instructions. But for the time being:

``` bash
npm install -g webpack gulp
npm install
```

and then run `gulp` which will compile and watch your files. You'll have to open the `index.html` in `./build` folder in order to view the app. :)
